### ISSUE TITLE
Elmish example

### ISSUE THREAD

**Issue by ImaginaryDevelopment** [fable-compiler/static-web-generator#11]
It would be lovely to have a elmish example of this.

**Comment by MangelMaxime** [comment]
What do you mean by Elmish?

This is a static website generator not something to write a SPA application.

**Comment by ImaginaryDevelopment** [comment]
maybe I wrongly believed that any react app even static-served could use the elmish pattern?

**Comment by MangelMaxime** [comment]
Well what you described is called in general Server Side Rendering. 

You can read more about it [here](https://safe-stack.github.io/docs/feature-ssr/), so yes this is doable.

But this is outside of the scope of this project for me.
