### ISSUE TITLE
Pages not always regenerated

### ISSUE THREAD

**Issue by MangelMaxime** [fable-compiler/static-web-generator#4]
I am using this repo for the Thot docs site but I found that the webpage is not always updated to the latest version of the generated JS.

In order to fix that, I use this `runScript`:

```fs
function runScript(scriptPath) {
    try {
        console.log("Running script")
        var childProcess = require("child_process");
        var path = require("path");
        var cp = childProcess.fork(scriptPath);
        cp.on("exit", function (code, signal) {
            if (code === 0) {
                console.log("Success");
            } else {
                console.log("Exit", { code: code, signal: signal });
            }
        });
        cp.on("error", console.error.bind(console));
    } catch (err) {
        console.error(err);
    }
}
```

Should we update the repo with it ?

**Comment by alfonsogarciacaro** [comment]
Hmm, that's strange, I haven't seen this (I think). But in any case it probably makes sense to run the script in a separate process so a PR would be nice 😄 I made many changes in the fable-compiler.github.io repo so probably we need to bring them here too.

Loosely related, I'm also using [a version number](https://github.com/fable-compiler/fableconf/blob/a260905586526dc12761f796f92a493c158d7be9/index.html#L16) that is [updated before publishing](https://github.com/fable-compiler/fableconf/blob/a260905586526dc12761f796f92a493c158d7be9/build.fsx#L73-L80) to prevent caching, we could integrate that here too :+1:

**Comment by MangelMaxime** [comment]
Will create the PR later when having more used the generator and see if anything else is missing :).

One thing I think about is: in my project, I also use `node-sass` to compile a local version of bulma so I can customize it. Would it make sense to add this option here too ? Because, IMO we never use a CSS framework without adding custom style etc.

**Comment by alfonsogarciacaro** [comment]
Yes, I'm always using node-sass recently too. It's much faster than Webpack style loader. Although you need to add the folder to the Workspace in chrome so it refreshes automatically, this probably needs to go in the README.

**Comment by MangelMaxime** [comment]
@alfonsogarciacaro For webpack-style loader you need to split the bundle in two parts. The JS part and the CSS part. Something like [that](https://github.com/MangelMaxime/fulma-demo/blob/master/webpack.config.js#L45-L51)

And in production mode I am using [ExtractTextPlugin](https://github.com/MangelMaxime/fulma-demo/blob/master/webpack.config.js#L59) plugin to generate a bundle.js and a style.css.

**Comment by alfonsogarciacaro** [comment]
Ah, I see. Interesting, didn't know about that...
